import { Property } from "./Property"

export type Element = {
    name : ElementName,
    properties : Property[]
}

export enum ElementName {
    Label,
    Button,
    StackFrame,
    TextBlock,
    TextBox,
    ComboBox,
    ListBox,
    ListView,
    RadioButton,
    CheckBox,
    Image,
    Grid,
    DockPanel,
    WrapPanel,
    StackPanel,
    Border,
    ScrollViewer,
    ProgressBar,
    Slider,
    TabControl,
    TabItem,
    Expander,
    Separator,
    Menu,
    MenuItem,
    ContextMenu,
    ToolTip,
    Popup,
    Canvas,
    Rectangle,
    Ellipse,
    Polygon,
    Line,
    Path,
    Viewbox,
    ContentControl,
    UserControl,
    ContentPresenter,
    ItemsControl,
    Frame,
    Page,
    Window,
}
